### ISSUE TITLE
Inconsistent naming conventions

### ISSUE THREAD

**Issue by tuliomonteazul** [nfe/woocommerce-nfe#1]
There some inconsistency on file names and class names.
Ex: The file [admin/class-wc-admin.php](https://github.com/nfe/woocommerce-nfe/blob/master/includes/admin/class-wc-admin.php) use hyphen for the filename and underscore for its class name (`WC_NFe_Admin`).
These other file [lib/Nfe/APIChildResource](https://github.com/nfe/woocommerce-nfe/blob/master/includes/lib/Nfe/APIChildResource.php) use camel case for both his file name and class name (`APIChildResource`).

**Comment by renatonascalves** [comment]
I have a biased view about this change, as I don't think strict name conversion must be followed here.

So I tried to make the files names as descriptive as possible. Any developer reading the code or searching a file will be able to know only by the file name where it it related to.
