### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by tuliomonteazul** [nfe/woocommerce-nfe#2]
The file `admin/class-wc-admin.php` is indenting with tabs on [line 28](https://github.com/nfe/woocommerce-nfe/blob/master/includes/admin/class-wc-admin.php#L28) and with spaces on [line 30](https://github.com/nfe/woocommerce-nfe/blob/master/includes/admin/class-wc-admin.php#L30).
This cause problems to read the code in some places (like Github) and can introduce unnecessary git diffs resulting in harder code reviews.
The project should have a indentation conventing (like 2 spaces) documented in some place (like README) and follow it.

**Comment by renatonascalves** [comment]
Good catch! Working on it right away!
